### ISSUE TITLE
GitHub Enterprise

### ISSUE THREAD

**Issue by MitchK** [chillu/github-dashing#22]
Does this project work with GitHub Enterprise? Does mean, how can I point to my own GitHub instance?

**Comment by chillu** [comment]
Hello Mitch, sorry for the late response! The underlying [octokit]() library used for Github communication supports custom API endpoints, presumably the only difference for Github Enterprise from an API perspective? You should be able to configure this as an environment variable (in `.env` or through `heroku config:set OCTOKIT_API_ENDPOINT=http://my-endpoint`). See http://octokit.github.io/octokit.rb/#Using_ENV_variables. I've had to fix the env var loading for this to work, can you confirm please?
