### ISSUE TITLE
Support for private travis-ci.com builds?

### ISSUE THREAD

**Issue by rberger** [chillu/github-dashing#25]
How hard would it be to support private travis-ci.com builds? I see that travis-ci.org is kind of hardwired in the code, plus would need to add auth tokens or something...

**Comment by brockoffdev** [comment]
:+1:

**Comment by chillu** [comment]
Hello! I've made this configurable through a new env var: `TRAVIS_API_ENDPOINT=https://api.travis-ci.com/`

**Comment by sergekukharev** [comment]
Guys, how do you specify Travis token? Whatever we try - doesn't work.
