### ISSUE TITLE
Set up works - but there are no widgets

### ISSUE THREAD

**Issue by PeterBi87** [chillu/github-dashing#30]
I am a beginner in ruby and dashing, so please be gentle :)

Issue:
Dashboard works, but there are no widgets to see.
I can see the background (dark grey) and the title "SilverStripe Contributions Dashboard"
But i cant see any widgets

What i did:
Copied all files to my ubuntu server
created an entry in my apache conf
configured a subpath (i did that before on another dashboard) as described here: https://github.com/Shopify/dashing/wiki/How-To:-Run-dashing-on-a-sub-path
bundle
copied content from .env.sample into .env and changed "ORGAS" github logiin and github token 
dashing start

I know there a some errors, but anyway the dashboard runs and i can access it.
Errors:

ERROR -- : ** [Raven] Unable to record event with remote Sentry server (R                                                                              aven::Error - Unknown transport scheme '')
ERROR -- : ** [Raven] /CHANGED/1.9.1/bundler/gems/raven-ruby-CHANGED/lib/raven/client.rb:87:in `transport'

CHANGED - I changed some part of the path

Already googled the errors, but didnt find any solutions. Does someone have an idea?

**Comment by chillu** [comment]
Hello Peter! Do you get any JavaScript errors in your browser? Are there any Github API calls visible in in your terminal when executing `dashing start`? I don't think the Raven errors have any relevance here, it's just for optional error logging through getsentry.com. I've just pushed a commit which should remove those errors when `SENTRY_DSN` isn't set in your environment.

**Comment by PeterBi87** [comment]
Thanks for your interest. I fixed it.
I guess the error was when i created the token from github API. You have to check more than the standard permissions.
You can close it!
